name: Create sandbox for PR

on:
  pull_request:
    branches:
      - main

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo running on branch ${GITHUB_REF##*/}
