name: Create sandbox for PR

on:
  pull_request:
    branches:
      - main

jobs:
  sandbox:
    - name: Extract branch name
    shell: bash
    run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    id: extract_branch
